### ISSUE TITLE
CSS Opacity

### ISSUE THREAD

**Issue by Master-Silver** [jirihybek/wa-mediabox#1]
In your CSS you use for the 'preview' and 'next' button opacity to hide them, but it does not realy hide the button. If you use 'display: none' instead you realy hide the button.

I hope that is the right way to send you this advice, because this is my first post on GitHub.

PS: you did really create a nice ligthbox ;-)

**Comment by jirihybek** [comment]
Thank you for you feedback. Yes, I know, but combining opacity and display is problematic for animation and must be scripted with delay. Eg. changing opacity to 1.0 and display to block will result in no animation, it just appears at once. I but I will look at it. Maybe just changing width and height to 0 without transition would be also a solution.

**Comment by Master-Silver** [comment]
For me the animations works fine, i did delet the opacity commands and ad for it the displays.

![lightboxcss](https://cloud.githubusercontent.com/assets/26323699/23835460/1b89268c-0768-11e7-8f32-2398faeaa74e.png)

**Comment by jirihybek** [comment]
I've tried your solution but it looses animation / fluent transition as I expected, arrow just appears at once instead of fade in / fade out.

**Comment by Master-Silver** [comment]
oh sorry, now i see what you mean. But for me the arrows don´t need animation and can just appear or disappear.
Other question, why did you set in your class "wa-mediabox-container" the "cursor" to "pointer"? Is there are reason for?

**Comment by jirihybek** [comment]
Because when you click on an image it navigates to next one and pointer cursor is there to show user that he can click on that.
